In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv("csv_result-chronic_kidney_disease_full.csv")
# CSV file had dimensional mismatch for 1 entry, that was rectified manually using excel
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [3]:
X=pd.DataFrame(X)
# X.head()

In [4]:
print(X)
print(y)

     0   1      2  3  4       5         6           7           8    9   ...  \
0    48  80   1.02  1  0       ?    normal  notpresent  notpresent  121  ...   
1     7  50   1.02  4  0       ?    normal  notpresent  notpresent    ?  ...   
2    62  80   1.01  2  3  normal    normal  notpresent  notpresent  423  ...   
3    48  70  1.005  4  0  normal  abnormal     present  notpresent  117  ...   
4    51  80   1.01  2  0  normal    normal  notpresent  notpresent  106  ...   
..   ..  ..    ... .. ..     ...       ...         ...         ...  ...  ...   
395  55  80   1.02  0  0  normal    normal  notpresent  notpresent  140  ...   
396  42  70  1.025  0  0  normal    normal  notpresent  notpresent   75  ...   
397  12  80   1.02  0  0  normal    normal  notpresent  notpresent  100  ...   
398  17  60  1.025  0  0  normal    normal  notpresent  notpresent  114  ...   
399  58  80  1.025  0  0  normal    normal  notpresent  notpresent  131  ...   

       14  15    16   17   18   19  20 

In [5]:
# Replace command works only on DataFrame
X = X.replace('?', np.nan)
X = X.replace(['normal','present','yes','good'], [1,1,1,1])
X = X.replace(['notpresent', 'abnormal','no','poor'], [0,0,0,0])
print(X)

     0   1      2  3  4    5    6    7    8    9   ...    14  15    16   17  \
0    48  80   1.02  1  0  NaN  1.0  0.0  0.0  121  ...  15.4  44  7800  5.2   
1     7  50   1.02  4  0  NaN  1.0  0.0  0.0  NaN  ...  11.3  38  6000  NaN   
2    62  80   1.01  2  3  1.0  1.0  0.0  0.0  423  ...   9.6  31  7500  NaN   
3    48  70  1.005  4  0  1.0  0.0  1.0  0.0  117  ...  11.2  32  6700  3.9   
4    51  80   1.01  2  0  1.0  1.0  0.0  0.0  106  ...  11.6  35  7300  4.6   
..   ..  ..    ... .. ..  ...  ...  ...  ...  ...  ...   ...  ..   ...  ...   
395  55  80   1.02  0  0  1.0  1.0  0.0  0.0  140  ...  15.7  47  6700  4.9   
396  42  70  1.025  0  0  1.0  1.0  0.0  0.0   75  ...  16.5  54  7800  6.2   
397  12  80   1.02  0  0  1.0  1.0  0.0  0.0  100  ...  15.8  49  6600  5.4   
398  17  60  1.025  0  0  1.0  1.0  0.0  0.0  114  ...  14.2  51  7200  5.9   
399  58  80  1.025  0  0  1.0  1.0  0.0  0.0  131  ...  15.8  53  6800  6.1   

      18   19   20   21   22   23  
0    1.0  1.0  

In [6]:
# Simple Imputer works only on array, hence converting Dataframe to Array
X = X.to_numpy() #Convert DataFrame to Array
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 0:24])
X[:, 0:24] = imputer.transform(X[:, 0:24])
print(X)

[[48.0 80.0 1.02 ... 1.0 0.0 0.0]
 [7.0 50.0 1.02 ... 1.0 0.0 0.0]
 [62.0 80.0 1.01 ... 0.0 0.0 1.0]
 ...
 [12.0 80.0 1.02 ... 1.0 0.0 0.0]
 [17.0 60.0 1.025 ... 1.0 0.0 0.0]
 [58.0 80.0 1.025 ... 1.0 0.0 0.0]]


In [7]:
X=pd.DataFrame(X) # Converting to DataFrame
print(X)

       0     1      2    3    4         5    6    7    8           9   ...  \
0    48.0  80.0   1.02  1.0  0.0  0.810484  1.0  0.0  0.0       121.0  ...   
1     7.0  50.0   1.02  4.0  0.0  0.810484  1.0  0.0  0.0  148.036517  ...   
2    62.0  80.0   1.01  2.0  3.0       1.0  1.0  0.0  0.0       423.0  ...   
3    48.0  70.0  1.005  4.0  0.0       1.0  0.0  1.0  0.0       117.0  ...   
4    51.0  80.0   1.01  2.0  0.0       1.0  1.0  0.0  0.0       106.0  ...   
..    ...   ...    ...  ...  ...       ...  ...  ...  ...         ...  ...   
395  55.0  80.0   1.02  0.0  0.0       1.0  1.0  0.0  0.0       140.0  ...   
396  42.0  70.0  1.025  0.0  0.0       1.0  1.0  0.0  0.0        75.0  ...   
397  12.0  80.0   1.02  0.0  0.0       1.0  1.0  0.0  0.0       100.0  ...   
398  17.0  60.0  1.025  0.0  0.0       1.0  1.0  0.0  0.0       114.0  ...   
399  58.0  80.0  1.025  0.0  0.0       1.0  1.0  0.0  0.0       131.0  ...   

       14    15      16        17   18   19   20   21   22   23

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


In [9]:
X_train = pd.DataFrame(X_train)
X_test = pd.DataFrame(X_test)

In [10]:
print(X_train)

            0      1         2         3         4         5         6   \
336       25.0   60.0      1.02       0.0       0.0       1.0       1.0   
64        55.0   80.0      1.01       0.0       0.0  0.810484       1.0   
55        35.0   80.0     1.005       3.0       0.0       0.0       1.0   
106       50.0   90.0  1.017408  1.016949  0.450142  0.810484  0.773134   
300       45.0   60.0      1.02       0.0       0.0       1.0       1.0   
..         ...    ...       ...       ...       ...       ...       ...   
323       43.0   80.0     1.025       0.0       0.0       1.0       1.0   
192       46.0  110.0     1.015       0.0       0.0  0.810484       1.0   
117  51.483376   70.0      1.02       0.0       0.0  0.810484  0.773134   
47        11.0   80.0      1.01       3.0       0.0  0.810484       1.0   
172       62.0   80.0      1.01       1.0       2.0  0.810484  0.773134   

           7         8           9   ...         14         15           16  \
336       0.0       

In [11]:
print(X_test)

       0          1         2         3         4         5         6    7   \
132  50.0  76.469072  1.017408  1.016949  0.450142       1.0  0.773134  0.0   
309  51.0       60.0      1.02       0.0       0.0  0.810484  0.773134  0.0   
341  63.0       70.0     1.025       0.0       0.0       1.0       1.0  0.0   
196  49.0      100.0      1.01       3.0       0.0       0.0       0.0  0.0   
246  48.0      110.0     1.015       3.0       0.0       0.0       1.0  1.0   
..    ...        ...       ...       ...       ...       ...       ...  ...   
14   68.0       80.0      1.01       3.0       2.0       1.0       0.0  1.0   
363  67.0       80.0     1.025       0.0       0.0       1.0       1.0  0.0   
304  33.0       80.0     1.025       0.0       0.0       1.0       1.0  0.0   
361  29.0       80.0      1.02       0.0       0.0       1.0       1.0  0.0   
329  33.0       60.0     1.025       0.0       0.0       1.0       1.0  0.0   

      8      9   ...    14    15       16   17   18

In [12]:
print(y_train)

['notckd' 'ckd' 'ckd' 'ckd' 'notckd' 'ckd' 'ckd' 'notckd' 'notckd'
 'notckd' 'notckd' 'notckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'notckd'
 'notckd' 'notckd' 'notckd' 'ckd' 'notckd' 'ckd' 'notckd' 'notckd' 'ckd'
 'notckd' 'ckd' 'notckd' 'ckd' 'ckd' 'notckd' 'ckd' 'notckd' 'ckd'
 'notckd' 'ckd' 'ckd' 'notckd' 'ckd' 'ckd' 'ckd' 'ckd' 'notckd' 'ckd'
 'ckd' 'notckd' 'notckd' 'ckd' 'ckd' 'notckd' 'ckd' 'ckd' 'ckd' 'ckd'
 'notckd' 'ckd' 'notckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'notckd' 'ckd'
 'notckd' 'ckd' 'ckd' 'ckd' 'notckd' 'ckd' 'notckd' 'ckd' 'ckd' 'ckd'
 'notckd' 'ckd' 'ckd' 'notckd' 'notckd' 'ckd' 'ckd' 'notckd' 'ckd' 'ckd'
 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'notckd' 'ckd' 'notckd' 'ckd' 'notckd'
 'ckd' 'ckd' 'notckd' 'notckd' 'ckd' 'ckd' 'ckd' 'notckd' 'ckd' 'ckd'
 'ckd' 'ckd' 'notckd' 'notckd' 'ckd' 'notckd' 'notckd' 'ckd' 'ckd' 'ckd'
 'ckd' 'ckd' 'notckd' 'ckd' 'ckd' 'ckd' 'ckd' 'notckd' 'notckd' 'notckd'
 'ckd' 'ckd' 'ckd' 'notckd' 'ckd' 'ckd' 'notckd' 'ckd' 'ckd' 'ckd' 'ckd'
 'ckd' 'ckd' '

In [13]:
 print(y_test)

['ckd' 'notckd' 'notckd' 'ckd' 'ckd' 'ckd' 'ckd' 'notckd' 'ckd' 'ckd'
 'ckd' 'ckd' 'ckd' 'notckd' 'ckd' 'ckd' 'notckd' 'ckd' 'ckd' 'ckd' 'ckd'
 'notckd' 'ckd' 'notckd' 'ckd' 'notckd' 'ckd' 'ckd' 'notckd' 'ckd' 'ckd'
 'notckd' 'notckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'notckd' 'ckd'
 'notckd' 'ckd' 'ckd' 'notckd' 'ckd' 'notckd' 'notckd' 'ckd' 'ckd' 'ckd'
 'ckd' 'notckd' 'ckd' 'notckd' 'notckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd'
 'notckd' 'ckd' 'notckd' 'ckd' 'notckd' 'ckd' 'ckd' 'ckd' 'notckd' 'ckd'
 'notckd' 'ckd' 'ckd' 'ckd' 'ckd' 'notckd' 'notckd' 'notckd' 'notckd']


In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [15]:
X_test=pd.DataFrame(X_test)
X_train=pd.DataFrame(X_train)
y_test=pd.DataFrame(y_test)
y_train=pd.DataFrame(y_train)

In [16]:
print(X_train)

           0         1         2         3         4         5         6   \
0   -1.509357 -1.183194  0.448853 -0.774825 -0.440322  0.607481  0.590331   
1    0.232128  0.284839 -1.431942 -0.774825 -0.440322 -0.024323  0.590331   
2   -0.928862  0.284839 -2.372339  1.650894 -0.440322 -2.726294  0.590331   
3   -0.058119  1.018856 -0.038662  0.047452  0.024491 -0.024323 -0.004698   
4   -0.348367 -1.183194  0.448853 -0.774825 -0.440322  0.607481  0.590331   
..        ...       ...       ...       ...       ...       ...       ...   
315 -0.464466  0.284839  1.389251 -0.774825 -0.440322  0.607481  0.590331   
316 -0.290317  2.486889 -0.491544 -0.774825 -0.440322 -0.024323  0.590331   
317  0.027990 -0.449177  0.448853 -0.774825 -0.440322 -0.024323 -0.004698   
318 -2.322050  0.284839 -1.431942  1.650894 -0.440322 -0.024323  0.590331   
319  0.638475  0.284839 -1.431942  0.033748  1.624858 -0.024323 -0.004698   

           7         8         9   ...        14        15        16  \
0  

In [17]:
print(X_test)

          0         1         2         3         4         5         6   \
0  -0.058119  0.025663 -0.038662  0.047452  0.024491  0.607481 -0.004698   
1  -0.000070 -1.183194  0.448853 -0.774825 -0.440322 -0.024323 -0.004698   
2   0.696525 -0.449177  1.389251 -0.774825 -0.440322  0.607481  0.590331   
3  -0.116169  1.752872 -1.431942  1.650894 -0.440322 -2.726294 -2.032492   
4  -0.174218  2.486889 -0.491544  1.650894 -0.440322 -2.726294  0.590331   
..       ...       ...       ...       ...       ...       ...       ...   
75  0.986772  0.284839 -1.431942  1.650894  1.624858  0.607481 -2.032492   
76  0.928723  0.284839  1.389251 -0.774825 -0.440322  0.607481  0.590331   
77 -1.044961  0.284839  1.389251 -0.774825 -0.440322  0.607481  0.590331   
78 -1.277159  0.284839  0.448853 -0.774825 -0.440322  0.607481  0.590331   
79 -1.044961 -1.183194  1.389251 -0.774825 -0.440322  0.607481  0.590331   

          7         8         9   ...        14        15        16        17  \
0  -0.

In [18]:
print(y_train)

          0
0    notckd
1       ckd
2       ckd
3       ckd
4    notckd
..      ...
315  notckd
316     ckd
317     ckd
318     ckd
319     ckd

[320 rows x 1 columns]


In [19]:
print(y_test)

         0
0      ckd
1   notckd
2   notckd
3      ckd
4      ckd
..     ...
75     ckd
76  notckd
77  notckd
78  notckd
79  notckd

[80 rows x 1 columns]


In [20]:
type(X_test)

pandas.core.frame.DataFrame

In [21]:
print(X_test)

          0         1         2         3         4         5         6   \
0  -0.058119  0.025663 -0.038662  0.047452  0.024491  0.607481 -0.004698   
1  -0.000070 -1.183194  0.448853 -0.774825 -0.440322 -0.024323 -0.004698   
2   0.696525 -0.449177  1.389251 -0.774825 -0.440322  0.607481  0.590331   
3  -0.116169  1.752872 -1.431942  1.650894 -0.440322 -2.726294 -2.032492   
4  -0.174218  2.486889 -0.491544  1.650894 -0.440322 -2.726294  0.590331   
..       ...       ...       ...       ...       ...       ...       ...   
75  0.986772  0.284839 -1.431942  1.650894  1.624858  0.607481 -2.032492   
76  0.928723  0.284839  1.389251 -0.774825 -0.440322  0.607481  0.590331   
77 -1.044961  0.284839  1.389251 -0.774825 -0.440322  0.607481  0.590331   
78 -1.277159  0.284839  0.448853 -0.774825 -0.440322  0.607481  0.590331   
79 -1.044961 -1.183194  1.389251 -0.774825 -0.440322  0.607481  0.590331   

          7         8         9   ...        14        15        16        17  \
0  -0.

In [22]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf',random_state = 0)
classifier.fit(X_train, y_train)

C:\Users\kgnan\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVC(random_state=0)

In [23]:
y_pred = classifier.predict(X_test)
y_test = y_test.to_numpy() #Converting DataFrame(PD) to arrays(NP)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['ckd' 'ckd']
 ['notckd' 'notckd']
 ['notckd' 'notckd']
 ['ckd' 'ckd']
 ['ckd' 'ckd']
 ['ckd' 'ckd']
 ['ckd' 'ckd']
 ['notckd' 'notckd']
 ['ckd' 'ckd']
 ['ckd' 'ckd']
 ['ckd' 'ckd']
 ['ckd' 'ckd']
 ['ckd' 'ckd']
 ['notckd' 'notckd']
 ['ckd' 'ckd']
 ['ckd' 'ckd']
 ['notckd' 'notckd']
 ['ckd' 'ckd']
 ['ckd' 'ckd']
 ['ckd' 'ckd']
 ['ckd' 'ckd']
 ['notckd' 'notckd']
 ['ckd' 'ckd']
 ['notckd' 'notckd']
 ['ckd' 'ckd']
 ['notckd' 'notckd']
 ['ckd' 'ckd']
 ['ckd' 'ckd']
 ['notckd' 'notckd']
 ['ckd' 'ckd']
 ['ckd' 'ckd']
 ['notckd' 'notckd']
 ['notckd' 'notckd']
 ['ckd' 'ckd']
 ['ckd' 'ckd']
 ['ckd' 'ckd']
 ['ckd' 'ckd']
 ['ckd' 'ckd']
 ['ckd' 'ckd']
 ['notckd' 'notckd']
 ['ckd' 'ckd']
 ['notckd' 'notckd']
 ['ckd' 'ckd']
 ['ckd' 'ckd']
 ['notckd' 'notckd']
 ['ckd' 'ckd']
 ['notckd' 'notckd']
 ['notckd' 'notckd']
 ['ckd' 'ckd']
 ['ckd' 'ckd']
 ['ckd' 'ckd']
 ['ckd' 'ckd']
 ['notckd' 'notckd']
 ['ckd' 'ckd']
 ['notckd' 'notckd']
 ['notckd' 'notckd']
 ['ckd' 'ckd']
 ['ckd' 'ckd']
 ['ckd' 'ckd']
 

In [24]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_pred, y_test)
print(acc*100, '%')

100.0 %


In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[52  0]
 [ 0 28]]


In [26]:
pre = cm[1][1]/(cm[1][1]+cm[0][1])
rec = cm[1][1]/(cm[1][1]+cm[1][0])
f = 2*pre*rec/(pre+rec)
print("f:", f)

f: 1.0
